name: Lets Start Patricia
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "and user not in [777000, 1087968824]"
          replace: "and user not in [777000, 1087968824, 1587091205]"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '❤️'Patricia
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Blaze_Oop
          commit_user_email: ubot491@gmail.com
          commit_author: Mr-Dark-Prince bot-supports.noreply.github.com>
